In [1]:
%matplotlib inline

import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
tracks_flock = pd.read_csv("LnB_tracks_MarToNov18.csv")


De volledige dataset is nu geladen op basis van de kolommen die nuttig kunnen zijn. Vervolgens filteren we de dataset op alleen de flock tracks. Dit zijn de tracks waarin regenbuien gemeten kunnen zijn. Door de dataset nu te sorteren op de waarde van de id's kan deze gemakkelijk vergeleken worden met de dataset bestaande uit alleen de flocks die geclassificeerd zijn als regen.


In [3]:
tracks_flock = tracks_flock.sort_values(["id"])

In [4]:
rain = pd.read_csv("LnB_raintrack_ids.csv")
rain = rain.sort_values(["id"])
rain_id = np.array(rain["id"])

In [5]:
rain = pd.read_csv("LnB_raintrack_ids.csv")
rain = rain.sort_values(["id"])
rain_id = np.array(rain["id"])
#print(rain[81850:81900])
# print(tracks_flock[136000:136010])

Beide datasets zijn nu gesorteerd. Door de overeenkomstige id's te vinden kan per rain track alle beschikbare informatie opgehaald worden. Deze is van belang om analyses te maken en de rain tracks te vergelijken met de overige tracks.

In [6]:
rain = []
binary_rain = []
bird = []
i = 220819
n = 0
for track in np.array(tracks_flock):
    if rain_id[i] == track[0]:
        i+=1
        #rain.append(track)
        binary_rain.append(1)
    else:
        binary_rain.append(0)
        #bird.append(track)
# print(rain)
print(bird)

[]


In [6]:
rain = pd.DataFrame(rain)
rain

[115052163 115248232 115267048]
[115262749]


In [7]:
bird = pd.DataFrame(bird)
bird

t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t


t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t


t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t


t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t


In [9]:
bird_flock = pd.DataFrame(bird_flock)
bird_flock

0                    1                    2   3         4        5   \
0  115262749  2019-09-11 05:17:19  2019-09-11 05:17:31   3   3.72443  1.60568   
1  115262750  2019-09-11 05:17:14  2019-09-11 05:17:34   6  18.43010  1.73331   

    6     7         8        9         10  11  
0  0.0  RaAz   29.4929  17.7310  0.764462   9  
1  0.0  RaAz  320.9160  11.7286  0.879623  14

In [10]:
rain_flock = pd.DataFrame(rain_flock)
rain_flock

Empty DataFrame
Columns: []
Index: []

In [7]:
# Selecteer kolom met index nummer uit data
def split_data(data, index):
    new_data = []
    for item in data:
        new_data.append(item[index])
    return new_data

In [26]:
rain = []
binary_rain = []
bird = []
i = 220819
n = 0
for track in np.array(tracks_flock):
    if rain_id[i] == track[0]:
        i+=1
        rain.append(track)
        binary_rain.append(1)
    else:
        binary_rain.append(0)
        bird.append(track)
# print(rain)
print(bird)

KeyboardInterrupt: 

In [10]:
df = tracks_flock
df = df.drop(['id','classification_id'],axis = 1)

se = pd.Series(rainbinarylist)
df['rainbinarylist'] = se.values
df = df.drop(['timestamp_start','timestamp_end','tracktype'],axis = 1)

df
df2 = df.mul(10000)
#df2.dtypes
df2.astype('int64').dtypes


df2 = df.astype(int)
print(df2.dtypes)
df2

rho_diff              int64
phi_diff              int64
theta_diff            int64
distance_travelled    int64
airspeed              int64
score                 int64
nr_of_plots           int64
rainbinarylist        int64
dtype: object


rho_diff  phi_diff  theta_diff  distance_travelled  airspeed  score  \
6              3         1           0                  29        17      0   
1             18         1           0                 320        11      0   
3             17         2           0                 251        16      0   
4            125         0           0                 153        21      0   
0             52        -1           0                 277        22      0   
8             12         1           0                  90        14      0   
2             85        -1           0                 298        21      0   
10             8         0           1                   6        20      0   
12           160         0           0                 177        24      0   
9             34         2           0                 110        15      0   
14            60        -2           0                  75        17      0   
5             20         1           0                 389        16      0   
7             62         2           0                 227        15      0   
13           117         0           0                 160        21      0   
16            13        -2           0                  43        17      0   
18           201         1           0                 432        10      0   
15            81         0           0                 164        13      0   
17             5         0           0                 166        16      0   
19            13        -1           0                  83        18      0   
20           139        -2           0                 167        19      0   
21            90         1           0                 174        11      0   
23             8         2           0                 119        16      0   
11             3         2           0                  10        15      0   
22           391         0           0                 437        23      0   
27             1         2           0                   1        17      0   
26           118         0           0                 255        12      0   
24           332         0           0                 493        15      0   
30           550        -1           0                 554        64      0   
28           222         2           0                 443        12      0   
29            60         0           0                 210        13      0   
...          ...       ...         ...                 ...       ...    ...   
999983       118         1           0                 180         8      0   
999987         1         2           0                   7        16      0   
999982       105         0           0                 236        15      0   
999979       105         1           0                 252        14      0   
999978        71         0           0                 201        17      0   
999960       275         1           0                 764        15      0   
999959       261         1           0                 596        12      0   
999970       377         0           0                 419        11      0   
999940       508         0           0                1460        15      0   
999989       196         0           0                 220        26      0   
999975        30        -1           0                 129        19      0   
999984       105        -2           0                 295        21      0   
999991        15        -1           0                  73        19      0   
999992        33        -1           0                 137        19      0   
999996       101         0           0                 177        13      0   
999988       283         2           0                 527        17      0   
999998         9         0           0                  27        16      0   
999974       655         0           0                1296        14      0   
999981       261         1           0                 408

In [11]:
#feature selection
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing

# load data
array = df2.values
print(array)
X = array[:,0:7]
print(X)
Y = array[:,7]
print(Y)
# feature extraction
model = LogisticRegression(solver='lbfgs')
rfe = RFE(model, 1)
fit = rfe.fit(X, Y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

[[  3   1   0 ...   0   9   0]
 [ 18   1   0 ...   0  14   0]
 [ 17   2   0 ...   0  14   0]
 ...
 [ 23   2   0 ...   0  38   0]
 [770   2   0 ...   0  68   0]
 [  5   0   0 ...   0 968   0]]
[[  3   1   0 ...  17   0   9]
 [ 18   1   0 ...  11   0  14]
 [ 17   2   0 ...  16   0  14]
 ...
 [ 23   2   0 ...  17   0  38]
 [770   2   0 ...  18   0  68]
 [  5   0   0 ...  17   0 968]]
[0 0 0 ... 0 0 0]
Num Features: 1
Selected Features: [False  True False False False False False]
Feature Ranking: [6 1 3 5 4 7 2]


In [22]:
#Standardize data
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
pca = PCA(n_components=2)

print(len(df) - df.count())
#No NaN, removed earlier

features = []
for col in df.columns:
    features.append(col)
#print(features)

# Separating out the features
x = df.loc[:, features].values

#y = df.loc[:,['target']].values

# Standardizing the features
x = StandardScaler().fit_transform(x)

#print(x)

principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents, columns = ['pc1', 'pc2'])

print(principalDf)

rho_diff              0
phi_diff              0
theta_diff            0
distance_travelled    0
airspeed              0
score                 0
nr_of_plots           0
rainbinarylist        0
dtype: int64
              pc1       pc2
0       -1.149683 -0.391313
1       -0.553988  0.451677
2       -0.621812  0.148890
3       -0.420945  0.017278
4       -0.035576  0.636209
5       -0.798811  0.393383
6       -0.528096 -0.497116
7       -1.191402 -0.796008
8       -0.596023 -0.774364
9       -1.152080 -0.634391
10      -0.711298  0.179923
11      -0.248937  0.352256
12      -0.218758  0.733863
13      -0.685785 -0.572030
14      -0.822284  0.228246
15      -0.556211 -0.389351
16      -0.952177 -0.339789
17      -0.619164  0.399169
18      -0.828302  0.040716
19      -0.382867  0.136537
20      -1.026720 -0.340809
21      -1.122283 -0.531501
22      -0.760779  0.390736
23       0.578757  0.088465
24      -1.782803 -1.717682
25      -0.720450 -0.138979
26      -0.119944 -0.593314
27       1.

In [25]:
plt.scatter(rain[4][0:100],rain[11][0:100])
plt.scatter(bird[4][0:100],bird[11][0:100])
plt.show()

IndexError: list index out of range