In [1]:
%matplotlib inline

import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
tracks_flock = pd.read_csv("LnB_tracks_MarToNov18.csv")
#usecols=['id', 'classification_id', 'rho_diff', 'phi_diff', 'distance_travelled']




De volledige dataset is nu geladen op basis van de kolommen die nuttig kunnen zijn. Vervolgens filteren we de dataset op alleen de flock tracks. Dit zijn de tracks waarin regenbuien gemeten kunnen zijn. Door de dataset nu te sorteren op de waarde van de id's kan deze gemakkelijk vergeleken worden met de dataset bestaande uit alleen de flocks die geclassificeerd zijn als regen.


In [3]:
# is_5 = tracks_flock["classification_id"] == 5
# tracks_flock = tracks_flock[is_5]
tracks_flock = tracks_flock.sort_values(["id"])
#98399542 = eerste rain track
# print(tracks_flock[136000:136010])
# print(tracks_flock[13750:13760])

In [4]:
rain = pd.read_csv("LnB_raintrack_ids.csv")
rain = rain.sort_values(["id"])
rain_id = np.array(rain["id"])
#print(rain[81850:81900])
# print(tracks_flock[136000:136010])

Beide datasets zijn nu gesorteerd. Door de overeenkomstige id's te vinden kan per rain track alle beschikbare informatie opgehaald worden. Deze is van belang om analyses te maken en de rain tracks te vergelijken met de overige tracks.

In [5]:
print(rain_id[82052])
print(np.array(tracks_flock["id"])[33814])
print()
# In CSV 2 komen rain_id[820052] en tracks_flock_id[33814] overeen.
print(rain_id[82101])
print(np.array(tracks_flock["id"])[386500])

99649080
115296568

99649135
115649254


In [6]:
#115262749
print(rain_id[220817:220820])
print([np.array(tracks_flock["id"])[0]])

[115052163 115248232 115267048]
[115262749]


In [7]:
# i = 0
# for rain in rain_id[220819:221000]:
#     print(rain)
#     print(np.array(tracks_flock["id"])[i])
#     if rain == np.array(tracks_flock["id"])[i]:
#         print('t')
#     i+=1
rain = []
i = 220819
for track_id in np.array(tracks_flock["id"]):
    if rain_id[i] == track_id:
        print('t')
        i+=1
        rain.append('1')
#     else:
#         rain.append('0')
print(rain)

    

t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t


t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t


t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t


t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t


t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t


In [8]:
i = 0
rain_flock = []
bird_flock = []
for track_id in np.array(tracks_flock["id"])[33814:33816]:
    print(i)
    if track_id in rain_id[82052:82060]:
        rain_flock.append(np.array(tracks_flock)[i])
        #print('+')
    else:
        bird_flock.append(np.array(tracks_flock)[i])
        #print('-')
    i += 1
print(rain_flock)
print()
print(bird_flock)

0
1
[]

[array([115262749, '2019-09-11 05:17:19', '2019-09-11 05:17:31', 3,
       3.72443, 1.60568, 0.0, 'RaAz', 29.4929, 17.730999999999995,
       0.764462, 9], dtype=object), array([115262750, '2019-09-11 05:17:14', '2019-09-11 05:17:34', 6,
       18.4301, 1.73331, 0.0, 'RaAz', 320.916, 11.7286,
       0.8796229999999999, 14], dtype=object)]


In [9]:
bird_flock = pd.DataFrame(bird_flock)
bird_flock

0                    1                    2   3         4        5   \
0  115262749  2019-09-11 05:17:19  2019-09-11 05:17:31   3   3.72443  1.60568   
1  115262750  2019-09-11 05:17:14  2019-09-11 05:17:34   6  18.43010  1.73331   

    6     7         8        9         10  11  
0  0.0  RaAz   29.4929  17.7310  0.764462   9  
1  0.0  RaAz  320.9160  11.7286  0.879623  14

In [10]:
rain_flock = pd.DataFrame(rain_flock)
rain_flock

Empty DataFrame
Columns: []
Index: []

In [11]:
# Selecteer kolom met index nummer uit data
def split_data(data, index):
    new_data = []
    for item in data:
        new_data.append(item[index])
    return new_data

In [12]:
def mean(lst):
    mean = sum(lst)/len(lst)
    return mean


def stddev(data, ddof=0):
    n = len(data)
    if n < 2:
        raise ValueError('variance requires at least two data points')
    ss = _ss(data)
    pvar = ss/(n-ddof)
    return pvar**0.5

In [13]:
phi_diff_rain = split_data(np.array(rain_flock), 4)
rho_diff_rain = split_data(np.array(rain_flock), 5)
theta_diff_rain = split_data(np.array(rain_flock), 6)
dis_travelled_rain = split_data(np.array(rain_flock), 8)
airspeed_rain = split_data(np.array(rain_flock), 9)

phi_diff_birds = split_data(np.array(tracks_flock)[13750:13850], 4)
rho_diff_birds = split_data(np.array(tracks_flock)[13750:13850], 5)
theta_diff_birds = split_data(np.array(tracks_flock)[13750:13850], 6)
dis_travelled_birds = split_data(np.array(tracks_flock)[13750:13850], 8)
airspeed_birds = split_data(np.array(tracks_flock)[13750:13850], 9)

print('RAIN:')
print('phi_diff: ', phi_diff_rain)
print()
print('rho_diff: ', rho_diff_rain)
print()
print('theta_diff: ', theta_diff_rain)
print()
print('BIRDS:')
print('phi_diff: ', phi_diff_birds)
print()
print('rho_diff: ', rho_diff_birds)
print()
print('theta_diff: ', theta_diff_birds)

RAIN:
phi_diff:  []

rho_diff:  []

theta_diff:  []

BIRDS:
phi_diff:  [79.6597, 153.247, 403.982, 214.767, 458.999, 213.941, 575.2909999999998, 627.981, 381.222, 135.094, 131.514, 232.675, 151.35399999999996, 367.891, 236.614, 127.434, 512.669, 106.117, 183.432, 220.444, 260.426, 238.232, 189.056, 249.812, 92.1803, 208.824, 169.49200000000005, 279.25, 351.309, 0.366703, 256.883, 146.113, 351.88699999999994, 357.793, 258.16900000000004, 179.107, 184.245, 397.131, 251.786, 281.328, 714.596, 256.085, 150.257, 139.594, 233.969, 79.2344, 353.01, 183.368, 270.293, 701.22, 1.39125, 477.441, 132.374, 90.0791, 114.795, 990.876, 70.0385, 748.8330000000002, 100.967, 425.608, 39.4416, 139.835, 180.46400000000003, 133.72899999999998, 87.0364, 100.835, 192.027, 11.927, 389.503, 213.73, 11.8561, 4.4840300000000015, 144.523, 258.374, 93.2928, 94.3355, 367.589, 124.946, 241.321, 49.2885, 342.483, 428.9380000000001, 96.6704, 38.116, 142.465, 282.519, 187.243, 286.261, 214.581, 361.711, 570.449000000000

In [14]:
'''import statistics
# Variabele phi
mean_phi_rain = mean(phi_diff_rain)
print('mean phi rain =', mean_phi_rain)
mean_phi_birds = mean(phi_diff_birds)
print('mean phi birds =', mean_phi_birds)
print()
std_phi_rain = statistics.stdev(phi_diff_rain)
print('std dev phi rain =', std_phi_rain)
std_phi_birds = statistics.stdev(phi_diff_birds)
print('std dev phi rain =', std_phi_birds)
print()

mean_rho_rain = mean(rho_diff_rain)
print('mean rho rain =', mean_rho_rain)
mean_rho_birds = mean(rho_diff_birds)
print('mean rho birds =', mean_rho_birds)
print()
std_rho_rain = statistics.stdev(rho_diff_rain)
print('std dev rho rain =', std_rho_rain)
std_rho_birds = statistics.stdev(rho_diff_birds)
print('std dev rho birds =', std_rho_birds)
print()

mean_dis_travelled_rain = mean(dis_travelled_rain)
print('mean distance travelled rain =', mean_dis_travelled_rain)
mean_dis_travelled_birds = mean(dis_travelled_birds)
print('mean distance travelled birds =', mean_dis_travelled_birds)
print()
std_dis_travelled_rain = statistics.stdev(dis_travelled_rain)
print('std dev distance travelled rain =', std_dis_travelled_rain)
std_dis_travelled_birds = statistics.stdev(dis_travelled_birds)
print('std dev distance travelled birds =', std_dis_travelled_birds)
print()

mean_airspeed_rain = mean(airspeed_rain)
print('mean airspeed rain =', mean_airspeed_rain)
mean_airspeed_birds = mean(airspeed_birds)
print('mean airspeed birds =', mean_airspeed_birds)
print()
std_airspeed_rain = statistics.stdev(airspeed_rain)
print('std dev airspeed rain =', std_airspeed_rain)
std_airspeed_birds = statistics.stdev(airspeed_birds)
print('std dev airspeed birds =', std_airspeed_birds)
'''

"import statistics\n# Variabele phi\nmean_phi_rain = mean(phi_diff_rain)\nprint('mean phi rain =', mean_phi_rain)\nmean_phi_birds = mean(phi_diff_birds)\nprint('mean phi birds =', mean_phi_birds)\nprint()\nstd_phi_rain = statistics.stdev(phi_diff_rain)\nprint('std dev phi rain =', std_phi_rain)\nstd_phi_birds = statistics.stdev(phi_diff_birds)\nprint('std dev phi rain =', std_phi_birds)\nprint()\n\nmean_rho_rain = mean(rho_diff_rain)\nprint('mean rho rain =', mean_rho_rain)\nmean_rho_birds = mean(rho_diff_birds)\nprint('mean rho birds =', mean_rho_birds)\nprint()\nstd_rho_rain = statistics.stdev(rho_diff_rain)\nprint('std dev rho rain =', std_rho_rain)\nstd_rho_birds = statistics.stdev(rho_diff_birds)\nprint('std dev rho birds =', std_rho_birds)\nprint()\n\nmean_dis_travelled_rain = mean(dis_travelled_rain)\nprint('mean distance travelled rain =', mean_dis_travelled_rain)\nmean_dis_travelled_birds = mean(dis_travelled_birds)\nprint('mean distance travelled birds =', mean_dis_travelled_

In [15]:
print()

In [16]:
rainbinarylist = []
i = 220819
for track_id in np.array(tracks_flock["id"]):
    if rain_id[i] == track_id:
#         print('t')
        i+=1
        rainbinarylist.append(1)
    else:
        rainbinarylist.append(0)
        
print(len(rainbinarylist))

print(len(df))


1000000


NameError: name 'df' is not defined

In [17]:
df = tracks_flock
df = df.drop(['id','classification_id'],axis = 1)

se = pd.Series(rainbinarylist)
df['rainbinary'] = se.values
df = df.drop(['timestamp_start','timestamp_end','tracktype'],axis = 1)

df
df2 = df.mul(10000)
#df2.dtypes
df2.astype('int64').dtypes


df2 = df.astype(int)
print(df2.dtypes)
df2

rho_diff              int64
phi_diff              int64
theta_diff            int64
distance_travelled    int64
airspeed              int64
score                 int64
nr_of_plots           int64
rainbinary            int64
dtype: object


rho_diff  phi_diff  theta_diff  distance_travelled  airspeed  score  \
6              3         1           0                  29        17      0   
1             18         1           0                 320        11      0   
3             17         2           0                 251        16      0   
4            125         0           0                 153        21      0   
0             52        -1           0                 277        22      0   
8             12         1           0                  90        14      0   
2             85        -1           0                 298        21      0   
10             8         0           1                   6        20      0   
12           160         0           0                 177        24      0   
9             34         2           0                 110        15      0   
14            60        -2           0                  75        17      0   
5             20         1           0                 389        16      0   
7             62         2           0                 227        15      0   
13           117         0           0                 160        21      0   
16            13        -2           0                  43        17      0   
18           201         1           0                 432        10      0   
15            81         0           0                 164        13      0   
17             5         0           0                 166        16      0   
19            13        -1           0                  83        18      0   
20           139        -2           0                 167        19      0   
21            90         1           0                 174        11      0   
23             8         2           0                 119        16      0   
11             3         2           0                  10        15      0   
22           391         0           0                 437        23      0   
27             1         2           0                   1        17      0   
26           118         0           0                 255        12      0   
24           332         0           0                 493        15      0   
30           550        -1           0                 554        64      0   
28           222         2           0                 443        12      0   
29            60         0           0                 210        13      0   
...          ...       ...         ...                 ...       ...    ...   
999983       118         1           0                 180         8      0   
999987         1         2           0                   7        16      0   
999982       105         0           0                 236        15      0   
999979       105         1           0                 252        14      0   
999978        71         0           0                 201        17      0   
999960       275         1           0                 764        15      0   
999959       261         1           0                 596        12      0   
999970       377         0           0                 419        11      0   
999940       508         0           0                1460        15      0   
999989       196         0           0                 220        26      0   
999975        30        -1           0                 129        19      0   
999984       105        -2           0                 295        21      0   
999991        15        -1           0                  73        19      0   
999992        33        -1           0                 137        19      0   
999996       101         0           0                 177        13      0   
999988       283         2           0                 527        17      0   
999998         9         0           0                  27        16      0   
999974       655         0           0                1296        14      0   
999981       261         1           0                 408

In [72]:
#feature selection
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing

# load data
array = df2.values
print(array)
X = array[:,0:7]
print(X)
Y = array[:,7]
print(Y)
# feature extraction
model = LogisticRegression(solver='lbfgs')
rfe = RFE(model, 1)
fit = rfe.fit(X, Y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

[[  3   1   0 ...   0   9   0]
 [ 18   1   0 ...   0  14   0]
 [ 17   2   0 ...   0  14   0]
 ...
 [ 23   2   0 ...   0  38   0]
 [770   2   0 ...   0  68   0]
 [  5   0   0 ...   0 968   0]]
[[  3   1   0 ...  17   0   9]
 [ 18   1   0 ...  11   0  14]
 [ 17   2   0 ...  16   0  14]
 ...
 [ 23   2   0 ...  17   0  38]
 [770   2   0 ...  18   0  68]
 [  5   0   0 ...  17   0 968]]
[0 0 0 ... 0 0 0]
Num Features: 1
Selected Features: [False  True False False False False False]
Feature Ranking: [6 1 3 5 4 7 2]


In [73]:
#Standardize data
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
pca = PCA(n_components=2)

print(len(df) - df.count())
#No NaN, removed earlier

features = []
for col in df.columns:
    features.append(col)
#print(features)

# Separating out the features
x = df.loc[:, features].values

#y = df.loc[:,['target']].values

# Standardizing the features
x = StandardScaler().fit_transform(x)

#print(x)

principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents, columns = ['pc1', 'pc2'])

print(principalDf)

#plt.scatter(principalDf[0],principalDf[1])

rho_diff              0
phi_diff              0
theta_diff            0
distance_travelled    0
airspeed              0
score                 0
nr_of_plots           0
rainbinary            0
dtype: int64
              pc1       pc2
0       -1.149683 -0.391313
1       -0.553988  0.451677
2       -0.621812  0.148890
3       -0.420945  0.017278
4       -0.035576  0.636209
...           ...       ...
999995   0.120047  0.631572
999996  -0.099683  0.086649
999997  -0.415587  0.528456
999998   4.775170 -0.456277
999999  17.907668  7.843123

[1000000 rows x 2 columns]


In [80]:
from sklearn.cluster import KMeans 
clusters = 2
  
kmeans = KMeans(n_clusters = clusters) 
kmeans.fit(df) 
  
print(kmeans.labels_)


[0 0 0 ... 0 1 1]


In [81]:
'''
print(kmeans.inertia_)

pca = PCA(3) 
pca.fit(df) 
  
pca_data = pd.DataFrame(pca.transform(df)) 
  
print(pca_data.head())
'''

'\nprint(kmeans.inertia_)\n\npca = PCA(3) \npca.fit(df) \n  \npca_data = pd.DataFrame(pca.transform(df)) \n  \nprint(pca_data.head())\n'

In [82]:
df3 = df2
se2 = pd.Series(kmeans.labels_)
df3['kmeans'] = se2.values
df3

rho_diff  phi_diff  theta_diff  distance_travelled  airspeed  score  \
6              3         1           0                  29        17      0   
1             18         1           0                 320        11      0   
3             17         2           0                 251        16      0   
4            125         0           0                 153        21      0   
0             52        -1           0                 277        22      0   
...          ...       ...         ...                 ...       ...    ...   
999995       229         0           0                 419        12      0   
999997       190         1           0                 441        13      0   
999986        23         2           0                  39        17      0   
999985       770         2           0                3106        18      0   
999218         5         0           0                5108        17      0   

        nr_of_plots  rainbinary  kmeans  
6                 9           0       0  
1                14           0       0  
3                14           0       0  
4                12           0       0  
0                18           0       0  
...             ...         ...     ...  
999995           24           0       0  
999997           23           0       0  
999986           38           0       0  
999985           68           0       1  
999218          968           0       1  

[1000000 rows x 9 columns]

In [83]:
print(len(df3.rainbinary))
print(len(df3.kmeans))

1000000
1000000


In [84]:
similars = 0
for i in range(len(df3.rainbinary)):
    if df3.rainbinary[i] == df3.kmeans[i]:
        similars+=1


In [85]:
print(similars/len(df3.rainbinary)*100,'%')

92.71770000000001 %
